# Generated by Django 5.1 on 2024-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_remove_responsemodel_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='response',
            field=models.CharField(max_length=1000),
        ),
    ]
